#!/usr/bin/env bash
# This script lists all running processes, including those without a TTY, in a user-oriented hierarchical format
ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
